theory All_Tests
imports
(* Valid *)
  AndTest
  BubblesortTest
  CountTest
  Cyclic_Linked_List_Test
  DerefTest
  DivTest
  EqTest
  FactorialTest
  FibonacciTest
  Global_Scope2_Test
  Global_Scope_Test
  LessTest
  Linked_List_Test
  Local_Scope_Test
  MergesortTest
  MinimumTest
  MinusTest
  ModTest
  MultTest
  NewTest
  NotTest
  OccursTest
  OrTest
  Outer_Scope_Test
  PlusTest
  QuicksortTest
  Returnv_Test
  SelectionsortTest
  StrLengthTest
  SubstTest
  WhileTest

(* Invalid *)
  "../InvalidTests/Address_And"
  "../InvalidTests/Address_Div"
  "../InvalidTests/Address_Indexl"
  "../InvalidTests/Address_Index"
  "../InvalidTests/Address_Integer_And"
  "../InvalidTests/Address_Integer_Div"
  "../InvalidTests/Address_Integer_Eq"
  "../InvalidTests/Address_Integer_Less"
  "../InvalidTests/Address_Integer_Mod"
  "../InvalidTests/Address_Integer_Mult"
  "../InvalidTests/Address_Integer_Or"
  "../InvalidTests/Address_Less"
  "../InvalidTests/Address_Minus"
  "../InvalidTests/Address_Mod"
  "../InvalidTests/Address_Mult"
  "../InvalidTests/Address_New"
  "../InvalidTests/Address_Not"
  "../InvalidTests/Address_Null_And"
  "../InvalidTests/Address_Null_Div"
  "../InvalidTests/Address_Null_Eq"
  "../InvalidTests/Address_Null_Less"
  "../InvalidTests/Address_Null_Mod"
  "../InvalidTests/Address_Null_Mult"
  "../InvalidTests/Address_Null_Or"
  "../InvalidTests/Address_Null_Plus"
  "../InvalidTests/Address_Null_Subst"
  "../InvalidTests/Address_Or"
  "../InvalidTests/Address_Plus"
  "../InvalidTests/Address_Returnv"
  "../InvalidTests/Address_Subst"
  "../InvalidTests/Few_Args_Callfunl"
  "../InvalidTests/Few_Args_Callfun"
  "../InvalidTests/Few_Args_Callfunv"
  "../InvalidTests/Integer_Address_And"
  "../InvalidTests/Integer_Address_Div"
  "../InvalidTests/Integer_Address_Eq"
  "../InvalidTests/Integer_Address_Less"
  "../InvalidTests/Integer_Address_Mod"
  "../InvalidTests/Integer_Address_Mult"
  "../InvalidTests/Integer_Address_Or"
  "../InvalidTests/Integer_Address_Plus"
  "../InvalidTests/Integer_Address_Subst"
  "../InvalidTests/Integer_Derefl"
  "../InvalidTests/Integer_Deref"
  "../InvalidTests/Integer_Indexl"
  "../InvalidTests/Integer_Index"
  "../InvalidTests/Integer_Null_And"
  "../InvalidTests/Integer_Null_Div"
  "../InvalidTests/Integer_Null_Eq"
  "../InvalidTests/Integer_Null_Less"
  "../InvalidTests/Integer_Null_Mod"
  "../InvalidTests/Integer_Null_Mult"
  "../InvalidTests/Integer_Null_Or"
  "../InvalidTests/Integer_Null_Plus"
  "../InvalidTests/Integer_Null_Subst"
  "../InvalidTests/Invalid_Address_Derefl"
  "../InvalidTests/Invalid_Address_Deref"
  "../InvalidTests/Invalid_Address_Free"
  "../InvalidTests/Many_Args_Callfunl"
  "../InvalidTests/Many_Args_Callfun"
  "../InvalidTests/Many_Args_Callfunv"
  "../InvalidTests/Negative_New"
  "../InvalidTests/No_Args_Callfunl"
  "../InvalidTests/No_Args_Callfun"
  "../InvalidTests/No_Args_Callfunv"
  "../InvalidTests/Non_Declared"
  "../InvalidTests/Non_Init"
  "../InvalidTests/Non_Terminating_Loop"
  "../InvalidTests/Null_Address_And"
  "../InvalidTests/Null_Address_Div"
  "../InvalidTests/Null_Address_Eq"
  "../InvalidTests/Null_Address_Less"
  "../InvalidTests/Null_Address_Mod"
  "../InvalidTests/Null_Address_Mult"
  "../InvalidTests/Null_Address_Or"
  "../InvalidTests/Null_Address_Plus"
  "../InvalidTests/Null_Address_Subst"
  "../InvalidTests/Null_Derefl"
  "../InvalidTests/Null_Deref"
  "../InvalidTests/Null_Index1"
  "../InvalidTests/Null_Index2"
  "../InvalidTests/Null_Indexl1"
  "../InvalidTests/Null_Indexl2"
  "../InvalidTests/Null_Integer_And"
  "../InvalidTests/Null_Integer_Div"
  "../InvalidTests/Null_Integer_Eq"
  "../InvalidTests/Null_Integer_Less"
  "../InvalidTests/Null_Integer_Mod"
  "../InvalidTests/Null_Integer_Mult"
  "../InvalidTests/Null_Integer_Or"
  "../InvalidTests/Null_Integer_Plus"
  "../InvalidTests/Null_Integer_Subst"
  "../InvalidTests/Null_Minus"
  "../InvalidTests/Null_New"
  "../InvalidTests/Null_Not"
  "../InvalidTests/Off_By_One"
  "../InvalidTests/Overflow1_Const"
  "../InvalidTests/Overflow1_Minus"
  "../InvalidTests/Overflow1_Plus"
  "../InvalidTests/Overflow1_Subst"
  "../InvalidTests/Overflow2_Const"
  "../InvalidTests/Overflow2_Minus"
  "../InvalidTests/Overflow2_Mod"
  "../InvalidTests/Overflow2_Plus"
  "../InvalidTests/Overflow2_Subst"
  "../InvalidTests/Reserved_Keywords_Auto"
  "../InvalidTests/Reserved_Keywords_Bool"
  "../InvalidTests/Reserved_Keywords_Break"
  "../InvalidTests/Reserved_Keywords_Case"
  "../InvalidTests/Reserved_Keywords_Char"
  "../InvalidTests/Reserved_Keywords_Complex"
  "../InvalidTests/Reserved_Keywords_Const"
  "../InvalidTests/Reserved_Keywords_Continue"
  "../InvalidTests/Reserved_Keywords_Default"
  "../InvalidTests/Reserved_Keywords_Double"
  "../InvalidTests/Reserved_Keywords_Else"
  "../InvalidTests/Reserved_Keywords_Enum"
  "../InvalidTests/Reserved_Keywords_Extern"
  "../InvalidTests/Reserved_Keywords_For"
  "../InvalidTests/Reserved_Keywords_Goto"
  "../InvalidTests/Reserved_Keywords_If"
  "../InvalidTests/Reserved_Keywords_Imaginary"
  "../InvalidTests/Reserved_Keywords_Inline"
  "../InvalidTests/Reserved_Keywords_Int"
  "../InvalidTests/Reserved_Keywords_Long"
  "../InvalidTests/Reserved_Keywords_Register"
  "../InvalidTests/Reserved_Keywords_Return"
  "../InvalidTests/Reserved_Keywords_Short"
  "../InvalidTests/Reserved_Keywords_Signed"
  "../InvalidTests/Reserved_Keywords_Sizeof"
  "../InvalidTests/Reserved_Keywords_Static"
  "../InvalidTests/Reserved_Keywords_Struct"
  "../InvalidTests/Reserved_Keywords_Switch"
  "../InvalidTests/Reserved_Keywords_Typedef"
  "../InvalidTests/Reserved_Keywords_Union"
  "../InvalidTests/Reserved_Keywords_Unsigned"
  "../InvalidTests/Reserved_Keywords_Void"
  "../InvalidTests/Reserved_Keywords_Volatile"
  "../InvalidTests/Reserved_Keywords_While"
  "../InvalidTests/Test_Keywords_Failed"
  "../InvalidTests/Test_Keywords_Num_Tests"
  "../InvalidTests/Test_Keywords_Passed"
  "../InvalidTests/Variable_Returnv"
  "../InvalidTests/Wrong_Scope"
  "../InvalidTests/Zero_Div"
  "../InvalidTests/Zero_Mod"
  "../InvalidTests/Zero_New"

begin

end
